name: Java CI - Compilation Check

# Se ejecuta en Pull Requests
on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # Compila todos los archivos .java del proyecto
      # Si este paso falla, todo el workflow fallará.
      - name: Compile project
        run: javac $(find . -name "*.java")
