name: Compile and Sync to GitLab

on:
  # Se activa solo en pushes a la rama principal
  push:
    branches:
      - main

jobs:
  compile_and_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # Si este paso falla, el workflow se detendrá aquí.
      - name: Compile project
        run: javac $(find . -name "*.java")

      # Este paso SOLO se ejecutará si la compilación fue exitosa.
      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Actions Sync"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/TU_USUARIO/TU_REPOSITORIO.git
          git push gitlab main
